### ISSUE TITLE
Backup creates empty file

### ISSUE THREAD

**Issue by grimsi** [joni1802/ts3-manager#11]
When using the "Create snapshot" functionality it downloads a file with the name `<timestamp>.backup` which is empty (0KB size, no content).
Maybe it's because I deployed the servermanager in a docker-compose stack together with the teamspeak server and host it behind a nginx reverse-proxy. Here is my config:
**docker-compose.yml:**
```yaml
version: '3.1'
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak-server
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10022:10022
      - 30033:30033
    volumes:
      - ./teamspeak-server:/var/ts3server/
    depends_on:
      - db
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: <censored>
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      TS3SERVER_QUERY_PROTOCOLS: ssh
  db:
    image: mariadb
    container_name: teamspeak-db
    restart: unless-stopped
    volumes:
      - ./teamspeak-db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: <censored>
      MYSQL_DATABASE: teamspeak  
  tsmanager:
    image: joni1802/ts3-manager
    container_name: teamspeak-tsmanager
    restart: unless-stopped
    ports:
      - 380:8080
    depends_on:
      - teamspeak
```
**nginx config:**
```
server {
    server_name tsmanager.<domain>;
	
    location / {
        proxy_pass http://localhost:380;
    }
	
    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = tsmanager.<domain>) {
        return 301 https://$host$request_uri;
    }

    server_name tsmanager.<domain>;
    listen 80;
    listen [::]:80;
    return 404;
}
```

I can log in using "teamspeak-server" (the docker service name) as the server URL and everything else seems to work fine, it's just the backup functionality that's broken
